
services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  webapp:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/c61b2d4e-2b04-4cc4-b093-810d04385adb
    networks:
      - app-network

  n8n:
    image: n8nio/n8n
    env_file:
      - .env
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network

volumes:
  postgres_data:
  n8n_data:

networks:
  app-network:
    driver: bridge
